gestionCommerce/urls.py
from django.urls import path
from . import views

app_name= "gestionCommerce"
urlpatterns = [
    path("", views.index, name="index"),
    path("addClient/", views.addC, name="addC"),
    path("addProduit/", views.addP, name="addP"),
    path("client/<int:client_id>/", views.clientt, name="client"),
    path("client/<int:client_id>/update/", views.updateC, name="updateC"),
    path("deleteC/<int:client_id>/", views.deleteC, name="deleteC"),
    path("client/<int:client_id>/commande/", views.commande, name="commande"),
    path("produit/<int:produit_id>/", views.produit, name="produit"),
    path("produit/<int:produit_id>/update/", views.updateP, name="updateP"),
    path("deleteP/<int:produit_id>/", views.deleteP, name="deleteP"),
    path("commande/<int:commande_id>/", views.commande, name="commande"),
    path("addCommande/", views.addCo, name="addCo"),
    path("commande/<int:commande_id>/update/", views.updateCo, name="updateCo"),
    path("deleteCo/<int:commande_id>/", views.deleteCo, name="deleteCo"),
]

projet/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

from projet import settings

urlpatterns = [
    path("gestionCommerce/", include("gestionCommerce.urls")),
    path("admin/", admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gestionCommerce/models.py
from django.db import models

# Create your models here.
class Client(models.Model):
    CIN = models.IntegerField()
    Nom = models.CharField(max_length=50)
    Prenom = models.CharField(max_length=50)
    Adresse = models.CharField(max_length=150)
    Telephone = models.IntegerField()
    Email = models.CharField(max_length=150)
    MotDePasse = models.CharField(max_length=150)
    def __str__(self):
        return f"{self.CIN} {self.Nom} {self.Prenom}"
    
class Produit(models.Model):
    Nom = models.CharField(max_length=50)
    Prix = models.FloatField(default=0.0)
    Description = models.TextField(blank=True)
    Image = models.ImageField(upload_to="produits/", blank=True, null=True)
    def __str__(self):
        return self.Nom + " (" + str(self.Prix) + ")"

class Commande(models.Model):
    num = models.IntegerField(default=0)
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    produits = models.ManyToManyField(Produit, through='CommandeProduit')
    date_commande = models.DateTimeField(blank= True, null=True)
    type_facture = models.CharField(max_length=20, choices=[('recu','Reçu'),('facture_proforma','Facture Proforma'),('facture','Facture')],default='reçu')
    def __str__(self):
        return f"Commande {self.num} de {self.client.Nom} {self.client.Prenom} le {self.date_commande.day}/{self.date_commande.month}/{self.date_commande.year}  "

class CommandeProduit(models.Model):
    commande = models.ForeignKey(Commande, on_delete=models.CASCADE)
    produit = models.ForeignKey(Produit, on_delete=models.CASCADE, null=True)
    Quantite = models.PositiveIntegerField(default=1)
    def __str__(self):
        return f"{self.produit.Nom} ({self.Quantite})"
    def montant(self):
        return self.produit.Prix * self.Quantite
        

gestionCommerce/forms.py
from django import forms
from .models import Client, Commande, CommandeProduit, Produit
from django.forms import modelformset_factory

class ClientRegistration(forms.ModelForm):
    class Meta:
        model = Client
        fields = ['CIN', 'Nom', 'Prenom', 'Adresse', 'Email', 'Telephone', 'MotDePasse']
        widgets = {
            'CIN': forms.NumberInput(attrs={'class':'form-control'}),
            'Nom': forms.TextInput(attrs={'class':'form-control'}),
            'Prenom': forms.TextInput(attrs={'class':'form-control'}),
            'Email': forms.EmailInput(attrs={'class':'form-control'}),
            'Adresse': forms.TextInput(attrs={'class':'form-control'}),
            'Telephone': forms.NumberInput(attrs={'class':'form-control'}),
            'MotDePasse': forms.PasswordInput(render_value=True,attrs={'class':'form-control'})

        }

class ProduitRegistration(forms.ModelForm):
    class Meta:
        model = Produit
        fields = ['Nom', 'Prix','Description', 'Image']
        widgets = {
            'Nom': forms.TextInput(attrs={'class':'form-control'}),
            'Prix': forms.NumberInput(attrs={'class':'form-control'}),
            'Description': forms.Textarea(attrs={'class':'form-control'}),
            'Image': forms.FileInput(attrs={'class':'form-control'}),
        }

class orderRegistration(forms.ModelForm):
    class Meta:
        model = CommandeProduit
        fields = ['produit', 'Quantite']
        widgets = {
            'produit': forms.Select(attrs={'class':'form-control'}),
            'Quantite': forms.NumberInput(attrs={'class':'form-control'}),
        }

OrderRegistrationFormSet = modelformset_factory(
    CommandeProduit,
    form=orderRegistration,
    extra=5, 
    can_delete=True,
)

class CommandeRegistration(forms.ModelForm):
    date_commande = forms.DateTimeField(
        widget=forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
        input_formats=['%d/%m/%Y %H:%M:%S', '%d/%m/%Y %H:%M', '%d/%m/%Y'],
    )
    class Meta:
        model = Commande
        fields = ['num', 'client', 'date_commande', 'type_facture']
        widgets = {
            'num': forms.NumberInput(attrs={'class':'form-control'}),
            'client': forms.Select(attrs={'class':'form-control'}),
            'date_commande': forms.DateTimeInput(attrs={'class':'form-control'}),
            'type_facture': forms.Select(attrs={'class':'form-control'}),
        }

gestionCommerce/views.py
from django.shortcuts import redirect, render, get_object_or_404, HttpResponseRedirect
from django.urls import reverse
from .models import Client, Commande, CommandeProduit, Produit
from .forms import ClientRegistration, CommandeRegistration, OrderRegistrationFormSet, ProduitRegistration
# Create your views here.

def index(request):
    client_list = Client.objects.all()
    produit_list=Produit.objects.all()
    commande_list=Commande.objects.all()
    context = {'client_list': client_list,
                'produit_list': produit_list,
                'commande_list': commande_list,
               }
    return render(request, "gestionCommerce/index.html",context)

def clientt(request, client_id):
    client = get_object_or_404(Client, pk=client_id)
    return render(request, "gestionCommerce/client.html", {"client":client})

def produit(request, produit_id):
    produit = get_object_or_404(Produit, pk=produit_id)
    return render(request, "gestionCommerce/produit.html", {"produit":produit})

def updateC(request, client_id):
    if request.method == 'POST':
        client = Client.objects.get(pk=client_id)
        fm = ClientRegistration(request.POST, instance=client)
        if fm.is_valid():
            fm.save()
    else:
        client = Client.objects.get(pk = client_id)
        fm = ClientRegistration(instance=client)

    return render(request, 'gestionCommerce/update.html',{'form':fm})

def deleteC(request, client_id):
    client = Client.objects.get(pk=client_id)
    if request.method == 'POST':
        client.delete()
        return redirect('gestionCommerce:index')
    return render(request, 'gestionCommerce/confirm_delete.html',{'client':client})

def updateP(request, produit_id):
    if request.method == 'POST':
        produit = Produit.objects.get(pk=produit_id)
        f = ProduitRegistration(request.POST, instance=produit)
        if f.is_valid():
            f.save()
    else:
        produit = Produit.objects.get(pk = produit_id)
        f = ProduitRegistration(instance=produit)

    return render(request, 'gestionCommerce/update.html',{'form':f})

def deleteP(request, produit_id):
    produit = Produit.objects.get(pk=produit_id)
    if request.method == 'POST':
        produit.delete()
        return redirect('gestionCommerce:index')
    return render(request, 'gestionCommerce/confirm_delete.html',{'produit':produit})

def addC(request):
    if request.method == 'POST':
        fm = ClientRegistration(request.POST)
        if fm.is_valid():
            cim = fm.cleaned_data['CIN']
            nm = fm.cleaned_data['Nom']
            pm = fm.cleaned_data['Prenom']
            em = fm.cleaned_data['Email']
            adr = fm.cleaned_data['Adresse']
            tm = fm.cleaned_data['Telephone']
            pw = fm.cleaned_data['MotDePasse']
            reg = Client(CIN = cim, Nom = nm, Prenom=pm, Email = em, Adresse= adr, Telephone= tm, MotDePasse = pw)
            reg.save()
            fm = ClientRegistration()
            return redirect(reverse('gestionCommerce:index'))
    else:
        fm = ClientRegistration()
    client = Client.objects.all()
    return render(request, 'gestionCommerce/add.html', {'form':fm, 'client':client})

def addP(request):
    if request.method == 'POST':
        f = ProduitRegistration(request.POST, request.FILES)
        if f.is_valid():
            nm = f.cleaned_data['Nom']
            pr = f.cleaned_data['Prix']
            des = f.cleaned_data['Description']
            img = f.cleaned_data['Image']
            reg = Produit(Nom = nm, Prix=pr, Description= des, Image = img)
            reg.save()
            f = ProduitRegistration()
            return redirect(reverse('gestionCommerce:index'))

    else:
        f = ProduitRegistration()
    produit = Produit.objects.all()
    return render(request, 'gestionCommerce/add.html', {'form':f, 'produit':produit})


def commande(request, commande_id):
    commande = get_object_or_404(Commande, pk=commande_id)
    return render(request, "gestionCommerce/commande.html", {"commande":commande})

def addCo(request):
    if request.method == 'POST':
        f = CommandeRegistration(request.POST)
        formset = OrderRegistrationFormSet(request.POST, prefix='order_formset')

        if f.is_valid() and formset.is_valid(): 
            num = f.cleaned_data['num']
            cl = f.cleaned_data['client']
            dt = f.cleaned_data['date_commande']
            tc = f.cleaned_data['type_facture']
            reg = Commande(num = num, client = cl, date_commande = dt, type_facture = tc)
            reg.save()

            for form in formset:
                if form.cleaned_data.get('produit'):
                    commande_produit = form.save(commit=False)
                    commande_produit.commande = reg
                    commande_produit.save()
 
            return redirect(reverse('gestionCommerce:index'))

    else:
        f = CommandeRegistration()
        formset = OrderRegistrationFormSet(prefix='order_formset')
    
    formset = OrderRegistrationFormSet(queryset=CommandeProduit.objects.none(), prefix='order_formset')

    commande = Commande.objects.all()
    return render(request, 'gestionCommerce/addCo.html', {'form':f, 'formset': formset, 'commande':commande})

def updateCo(request, commande_id):
    commande = Commande.objects.get(pk=commande_id)

    if request.method == 'POST':
        fm = CommandeRegistration(request.POST, instance=commande)
        formset = OrderRegistrationFormSet(request.POST, prefix='order_formset', queryset=commande.commandeproduit_set.all())

        if fm.is_valid() and formset.is_valid():
            fm.save()

            # Process each form in the formset
            for form in formset:
                if form.cleaned_data.get('DELETE'):
                    # If the form has the DELETE field checked, delete the associated bought product
                    if form.instance.pk is not None:
                        form.instance.delete()
                else:
                    # If the form is not marked for deletion, save it with the updated quantity
                    if form.cleaned_data.get('produit'):
                        form.save(commit=False)
                        form.instance.commande = commande
                        form.save()
            # Add a new form for adding a new bought product
            formset.extra += 1

            fm = CommandeRegistration(instance=commande)
            formset = OrderRegistrationFormSet(prefix='order_formset', queryset=commande.commandeproduit_set.all())
            return redirect(reverse('gestionCommerce:commande', kwargs={'commande_id': commande.id}))
    else:
        fm = CommandeRegistration(instance=commande)
        formset = OrderRegistrationFormSet(prefix='order_formset', queryset=commande.commandeproduit_set.all())

    return render(request, 'gestionCommerce/updateCo.html', {'form': fm, 'formset': formset, 'commande': commande})


def deleteCo(request, commande_id):
    commande = Commande.objects.get(pk=commande_id)
    if request.method == 'POST':
        commande.delete()
        return redirect('gestionCommerce:index')
    return render(request, 'gestionCommerce/confirm_delete.html',{'commande':commande})
    

gestionCommerce/templates/gestionCommerce/add.html
{% extends 'gestionCommerce/basic.html' %}
{% block title %}Gestion Commerce | Ajouter un client/produit{% endblock %}
{% block content %}
<div class="container">
  <div class="jumbotron text-center mt-5">
    <h1 class="display-4">Ajouter un nouveau client/produit</h1>
  </div>
  <div class="col-md-6">
    <div class="card mb-4">
      <div class="card-body">
        <form action="" method="POST" enctype="multipart/form-data">
          {% csrf_token %} 
          
          {{form.as_p}}
          <div style="text-align: center;">
            <input type="submit" class="btn btn-success" style="border-radius: 7%; height:40px; text-decoration: none;display: inline-block; text-align: center;   border: none;
                outline: none;
                padding: 8px;
                margin: 0;" value="Ajouter" />
            <a href="{% url 'gestionCommerce:index' %}" style="border-radius: 7%; height:40px; text-decoration: none; background-color: #7097c2; color: #ffffff;display: inline-block; text-align: center;   border: none;
                outline: none;
                padding: 8px;
                margin: 0;">Retour</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}
{% block contents %}
{% endblock %}

gestionCommerce/templates/gestionCommerce/addCo.html
{% extends 'gestionCommerce/basic.html' %}
{% block title %}Gestion Commerce | Ajouter une commande{% endblock %}
{% block content %}
<div class="container">
    <div class="jumbotron text-center mt-5">
        <h1 class="display-4">Ajouter une nouvelle commande</h1>
    </div>
    <div class="col-md-6">
        <div class="card mb-4">
            <div class="card-body">
                <form action="" method="POST" enctype="multipart/form-data">
                    {% csrf_token %}

                    {{ form.num.label_tag }}
                    {{ form.num }}
                    {{ form.client.label_tag }}
                    {{ form.client }}
                    {{ form.date_commande.label_tag }}
                    {{ form.date_commande }}
                    {{ form.type_facture.label_tag }}
                    {{ form.type_facture }}
                    
                    <hr>

                    {{ formset.management_form }}
                    {% for form in formset %}
                    {{ form.id }}
                    {{ form.produit.label_tag }}
                    {{ form.produit }}
                    {{ form.Quantite.label_tag }}
                    {{ form.Quantite }}
                    <br>
                    {% endfor %}

                    <div style="text-align: center;">
                        <input type="submit" class="btn btn-success" style="border-radius: 7%; height:40px; text-decoration: none;display: inline-block; text-align: center;   border: none;
                outline: none;
                padding: 8px;
                margin: 0;" value="Ajouter" />
                        <a href="{% url 'gestionCommerce:index' %}" style="border-radius: 7%; height:40px; text-decoration: none; background-color: #7097c2; color: #ffffff;display: inline-block; text-align: center;   border: none;
                outline: none;
                padding: 8px;
                margin: 0;">Retour</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block contents %}
{% endblock %}

gestionCommerce/templates/gestionCommerce/basic.html
<!DOCTYPE html>
{% load static %}
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'gestionCommerce/css/bootstrap.css' %}">
    <title>{% block title %} {% endblock %}</title>
</head>

<body>
    <div>
        <nav class="navbar navbar-expand-lg navbar-light"
            style="padding: 0.5rem; background-color: #265f88; font-family:serif; font-size: large; font-weight: bold;">
            <!-- <a class="navbar-brand">    icon</a> -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-item nav-link active" href="{% url 'gestionCommerce:index' %}"
                        style="color: #ffdada; text-decoration: underline;">Accueil</a>
                    <a class="nav-item nav-link" href="#contact" style="color: #d6d6d6;">Contact</a>
                </div>
            </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
    
    {% block contents %}
    <div class="container">
        <div class="jumbotron text-center mt-5">
            <h1 class="display-4">Bienvenue sur Gestion Commerce</h1>
            <p class="lead">Votre solution de gestion de produits, clients et commandes.</p>
        </div>

        <div class="row">
            <div class="col-md-6">
                <div class="card mb-4">
                    <div class="card-body">
                        {% block clients %}
                        {% endblock %}
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card mb-4">
                    <div class="card-body">
                        {% block produits %}
                        {% endblock %}
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="card mb-4">
                    <div class="card-body">
                        {% block commandes %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

    <div id="contact">
        <footer class="bg-light text-center text-lg-start" style="padding: 1%;">
            <div class="text-center p-3">
                <a href="https://www.linkedin.com/in/sara-drine-2a9651228/" target="_blank"
                    style="color: #171212; text-decoration: none;">
                    <img src="/media/linkedin.png" alt="LinkedIn Logo"
                        style="vertical-align: middle; margin-right: 5px; width: 25px;">
                    Sara Drine
                </a>
            </div>
            <div class="text-center p-3">
                <a href="https://github.com/saradrine/projetGestionCommerce" target="_blank"
                    style="color: #171212; text-decoration: none;">
                    <img src="/media/github.png" alt="GitHub Logo"
                        style="vertical-align: middle; margin-right: 5px; width: 25px;"> Source code
                </a>
            </div>
            <div class="text-center p-3">
                <p style="color: #171212;">&copy; 2023 First Django App</p>
            </div>
        </footer>
    </div>


    <script src="{% static 'gestionCommerce/js/jquery.js' %}"></script>
    <script src="{% static 'gestionCommerce/js/bootstrap.js' %}"></script>

</body>

</html>

gestionCommerce/templates/gestionCommerce/client.html
{% extends 'gestionCommerce/basic.html' %}
{% block title %}Gestion Commerce | Details de client{% endblock %}
{% block content %}
<div class="container" style="margin-top: 4rem;">
    <div class="col-md-6">
        <div class="card mb-4">
            <div class="card-body">
                <div class="jumbotron text-center ">
                    <h3 class="display-4"><b><i>{{ client.Nom }} {{ client.Prenom }}</i></b></h3>
                </div>
                <ul>
                    <li><b>CIN:</b> {{ client.CIN }}</li>
                    <li><b>Adresse:</b> {{ client.Adresse }}</li>
                    <li><b>Pour contacter ce client:</b></li>
                    <ul><b>Telephone:</b> {{ client.Telephone }}</ul>
                    <ul><b>Email:</b> {{ client.Email }}</ul>
                </ul>
                <div style="text-align: center;">
                    <a href="{% url 'gestionCommerce:updateC' client.id %}" class="btn btn-warning">Modifier</a>
                    <!-- <form action="{% url 'gestionCommerce:deleteC' client.id %}" method="POST" class="d-inline">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-danger" value="Supprimer">
                    </form> -->
                    <a href="{% url 'gestionCommerce:deleteC' client.id %}" class="btn btn-danger">Supprimer</a>
                    <br>
                    <a href="{% url 'gestionCommerce:index' %}"
                        style="border-radius: 7%; width: 100px; text-decoration: none; background-color: #7097c2; color: #ffffff;display: inline-block; text-align: center; border: none; outline: none; padding: 1.5%; margin: 5px;">Retour</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block contents %}
{% endblock %}

gestionCommerce/templates/gestionCommerce/commande.html
{% extends 'gestionCommerce/basic.html' %}
{% block title %}Gestion Commerce | Details de commande{% endblock %}
{% block content %}
<div class="container" style="margin-top: 4rem;">
    <div class="col-md-6">
        <div class="card mb-4">
            <div class="card-body">
                <div class="jumbotron text-center ">
                    <h1 class="display-4"><b><i>{{ commande.num }}</i></b></h1>
                </div>

                <ul><b>Client:</b> {{ commande.client }}</ul>
                <ul><b>Date:</b> {{ commande.date_commande }}</ul>
                <ul><b>Type de facture:</b> {{ commande.type_facture }}</ul>
                <ul><b>Produit:</b>
                    {% for commande_produit in commande.commandeproduit_set.all %}
                    <ul>* {{ commande_produit.produit.Nom }} (Quantité: {{ commande_produit.Quantite }})</ul>
                    {% endfor %}
                </ul>

                <div style="text-align: center;">
                    <a href="{% url 'gestionCommerce:updateCo' commande.id %}" class="btn btn-warning">Modifier</a>
                    <!-- <form action="{% url 'gestionCommerce:deleteCo' commande.id %}" method="POST" class="d-inline">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-danger" value="Supprimer">
                    </form> -->
                    <a href="{% url 'gestionCommerce:deleteCo' commande.id %}" class="btn btn-danger">Supprimer</a>

                    <br>
                    <a href="{% url 'gestionCommerce:index' %}"
                        style="border-radius: 7%; width: 100px; text-decoration: none; background-color: #7097c2; color: #ffffff;display: inline-block; text-align: center; border: none; outline: none; padding: 1.5%; margin: 5px;">Retour</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block contents %}
{% endblock %}

gestionCommerce/templates/gestionCommerce/index.html
{% extends 'gestionCommerce/basic.html' %} 
{% block title %}Gestion Commerce | Page d'accueil{% endblock %}


        {% block clients %}
            {% if client_list %}
                <h2 class="card-title">Liste des Clients <a href="{% url 'gestionCommerce:addC' %}" style="border-radius: 50%; text-decoration: none; background-color: #7097c2; color: #fff; width: 30px; line-height: 25px;font-size: 30px;display: inline-block; text-align: center;">&plus;</a></h2>
                <p class="card-text">Consultez la liste de tous vos clients.</p>
                <table class="table table-hover">
                    <thead>
                        <tr>
                        <th scope="col">ID</th>
                        <th scope="col">CIN</th>
                        <th scope="col">Nom</th>
                        <th scope="col">Prenom</th>
                        <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for client in client_list %}
                        <tr>
                        <th scope="row">{{client.id}}</th>
                        <td scope="row"> {{client.CIN}}</td>
                        <td scope="row"> {{client.Nom}}</td>
                        <td scope="row">{{client.Prenom}}</td>
                        <td scope="row"><a href="{% url 'gestionCommerce:client' client.id %}" style="border-radius: 10%; text-decoration: none; background-color: #7097c2; color: #fff; width: 30px; line-height: 25px;font-size: 30px;display: inline-block; text-align: center;">&rarr;</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h4>Aucun client n'a été ajouté  <a href="{% url 'gestionCommerce:addC' %}" style="border-radius: 50%; text-decoration: none; background-color: #7097c2; color: #fff; width: 30px; line-height: 25px;font-size: 30px;display: inline-block; text-align: center;">&plus;</a></h4>
            {% endif %}
        {% endblock %}
        {% block produits %}
            {% if produit_list %}
                <h2 class="card-title">Liste des Produits <a href="{% url 'gestionCommerce:addP' %}" style="border-radius: 50%; text-decoration: none; background-color: #7097c2; color: #fff; width: 30px; line-height: 25px;font-size: 30px;display: inline-block; text-align: center;">&plus;</a></h2>
                <p class="card-text">Explorez notre gamme de produits.</p>
                <table class="table table-hover">
                    <thead>
                        <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Nom</th>
                        <th scope="col"></th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for produit in produit_list %}
                        <tr>
                        <th scope="row">{{produit.id}}</th>
                        <td scope="row"> {{produit.Nom}}</td>
                        <td scope="row"><a href="{% url 'gestionCommerce:produit' produit.id %}" style="border-radius: 10%; text-decoration: none; background-color: #7097c2; color: #fff; width: 30px; line-height: 25px;font-size: 30px;display: inline-block; text-align: center;">&rarr;</a></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <h4>Aucun produit n'a été ajouté  <a href="{% url 'gestionCommerce:addP' %}" style="border-radius: 50%; text-decoration: none; background-color: #7097c2; color: #fff; width: 30px; line-height: 25px;font-size: 30px;display: inline-block; text-align: center;">&plus;</a></h4>
            {% endif %}
        {% endblock %}

        {% block commandes %}
        {% if commande_list %}
        <h2 class="card-title">Liste des Commandes <a href="{% url 'gestionCommerce:addCo' %}"
                style="border-radius: 50%; text-decoration: none; background-color: #7097c2; color: #fff; width: 30px; line-height: 25px;font-size: 30px;display: inline-block; text-align: center;">&plus;</a>
        </h2>
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">Num Commande</th>
                    <th scope="col">Client</th>
                    <th scope="col">Date</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for commande in commande_list %}
                <tr>
                    <th scope="row">{{commande.num}}</th>
                    <td scope="row"> {{commande.client}}</td>
                    <td scope="row">{{commande.date_commande}}</td>
                    <td scope="row"><a href="{% url 'gestionCommerce:commande' commande.id %}"
                            style="border-radius: 10%; text-decoration: none; background-color: #7097c2; color: #fff; width: 30px; line-height: 25px;font-size: 30px;display: inline-block; text-align: center;">&rarr;</a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% else %}
        <h4>Aucune commande <a href="{% url 'gestionCommerce:addCo' %}"
                style="border-radius: 50%; text-decoration: none; background-color: #7097c2; color: #fff; width: 30px; line-height: 25px;font-size: 30px;display: inline-block; text-align: center;">&plus;</a>
        </h4>
        {% endif %}
        {% endblock %}

gestionCommerce/templates/gestionCommerce/produit.html
{% extends 'gestionCommerce/basic.html' %}
{% block title %}Gestion Commerce | Details de produit{% endblock %}
{% block content %}
<div class="container" style="margin-top: 4rem;">
    <div class="col-md-6">
        <div class="card mb-4">
            <div class="card-body">
                <div class="jumbotron text-center ">
                    <h4 class="display-4"><b><i>{{ produit.Nom }}</i></b></h4>
                </div>
                <ul>
                    <li><b>Description:</b> {{ produit.Description }}</li>
                    <li><b>Prix:</b> {{ produit.Prix }}dt</li>
                    <img src="{{ produit.Image.url }}" alt="{{ produit.Nom }}" style="max-width: 250px;">
                </ul>
                <div style="text-align: center;">
                    <a href="{% url 'gestionCommerce:updateP' produit.id %}" class="btn btn-warning">Modifier</a>
                    <!-- <form action="{% url 'gestionCommerce:deleteP' produit.id %}" method="POST" class="d-inline">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-danger" value="Supprimer">
                    </form> -->
                    <a href="{% url 'gestionCommerce:deleteP' produit.id %}" class="btn btn-danger">Supprimer</a>
                    <br>
                    <a href="{% url 'gestionCommerce:index' %}"
                        style="border-radius: 7%; width: 100px; text-decoration: none; background-color: #7097c2; color: #ffffff;display: inline-block; text-align: center; border: none; outline: none; padding: 1.5%; margin: 5px;">Retour</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}
{% block contents %}
{% endblock %}